---
title: "Simulated Canadian Election"
author: "Xiye Zhong, Jiesen Cui, Ruihan Zhang"
date: "10/8/2020"
output: pdf_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rstan)
example(stan_model, run.dontrun = TRUE)
#install.packages("brms")
#install.packages("tidyverse")
#install.packages("survey")
#install.packages("sampling")
library(grid)
library(sampling)
library(survey)
library(brms)
library(tidyverse)
```

```{r}
simulated_data <- tibble(
  #Check whether they are eligible.
  Citizenship = sample(x = c("yes","no"), size = 10000, 
                       replace = TRUE, prob = c(0.9, 0.1)),
  #Build up the distribution of ages.
   Age_Group = sample(x = c("Under 18", "18 to 30", "30 to 39", "40 to 49", "50 to 59", "60 to 69", "70 and above"), size = 10000, replace = TRUE, 
                      prob = c(0.1908, 0.1583, 0.1393, 0.1277, 0.1367, 0.1244, 0.1228)),
  #Build up the distribution of annual income.
  Annual_Income = sample(x = c("Under $10k", "$10k to $24.9k", "$25k to $49.9k", "$50k to $99.9k", "$100k to $249.9k", "Over $250k"), size = 10000, 
                         replace = TRUE, prob = c(0.11, 0.24, 0.29, 0.26, 0.086, 0.01)),
  #Build up the distribution of gender.
  Gender = sample(x=c("Male", "Female", "Transgender", "Unknown"), size = 10000, replace = TRUE, prob = c(0.48, 0.48, 0.01, 0.03)),
  #Build up the distribution of probability of vote.
  Vote = sample(x = c("CPC", "LPC", "NDP", "BQ", "GPC", "OTHER", "Would not vote"),
                size = 10000, replace = TRUE, prob = c(0.3, 0.36, 0.2, 0.07, 0.04, 0.02, 0.01)),
  #Build up the distribution of regions..
  Region = sample(x = c("AB", "BC","MB", "NB", "NL", "NS", "NT", "NU", "ON", "PE","QC", "SK", "YT"), size = 10000, replace = TRUE, prob = c(0.1157, 0.1322, 0.036, 0.021, 0.015, 0.001, 0.026, 0.001, 0.3826, 0.004, 0.2323, 0.0312, 0.001)),
  #Build up the distribution of scales of people knowing about Liberal Party's promises.
  Scale = sample(x = c(1:5), size = 10000, replace = TRUE, prob = c(0.1, 0.2, 0.35, 0.15, 0.2))
  )
```

```{r}
N<-nrow(simulated_data)
n <-500
s<-srswor(n,N)
s
data.srswor<-getdata(simulated_data,s) #Use SRSWOR method to get 500 samples from the simulated dataset.
```

```{r}
data.srswor %>%
  mutate(Vote = as_factor(Vote)) %>%
  ggplot(aes(x = Vote)) +
  geom_bar() +
  labs(
    title = "Figure 1: Distribution of people's vote for different parties",
    x = "Parties",
    y = "Number of respondents",
    caption = "Source: Simulated Dataset"
  ) #Plot a bar chart to show people's tendency of voting for a party.

```

```{r}
data.srswor%>%
  ggplot(aes(x = Annual_Income, fill = Vote))+
  geom_bar(position = "fill") +
  labs(
    title = "Figure 2: The distribution of voting in different groups of anuual income",
    X = "Annual Income",
    y = "Percentage",
    cation = "Source: Simulated Statistics"
  )

#Plot a stacked bar chart to show people's tendency of voting for a party who are grouped by annual income.
```
```{r}
test_data <- tibble(Age_Group = sample(x = c("Under 18", "18 to 30", "30 to 39", "40 to 49", "50 to 59", "60 to 69", "70 and above"), size = 10000, replace = TRUE, 
                      prob = c(0.1908, 0.1583, 0.1393, 0.1277, 0.1367, 0.1244, 0.1228)),
                    Annual_Income = sample(x = c("Under $10k", "$10k to $24.9k", "$25k to $49.9k", "$50k to $99.9k", "$100k to $249.9k", "Over $250k"), size = 10000, 
                         replace = TRUE, prob = c(0.11, 0.24, 0.29, 0.26, 0.086, 0.01)),
                    Vote = sample(x = c("yes","no"),
                size = 10000, replace = TRUE, prob = c(0.36,0.64)),
                    
)
#build a dataset which contains age groups, annual income and the probability of vote for LPC.
```




```{r}
model_1 <- brm(Vote ~ Age_Group + Annual_Income,
            data = test_data,
            family = bernoulli()
            )
summary(model_1)
plot(model_1) 
#Use brm to find the regression between the probability of vote for LPC and age groups and annual income.
```

```{r}
conditional_effects(model_1)
#Show the conditional effects of ages and annual income.
```
